version: '3'
services:
  hk-nginx:
   container_name: hk-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - event-sender
   - zipkin

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

  event-sender:
    restart: always
    build: ./rabbitmq-event-sender
    working_dir: /rabbitmq-event-sender
    volumes:
      - ./rabbitmq-event-sender:/rabbitmq-event-sender
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - zipkin
